# Exercise 5A NumPy Fundamentals

This exercise covers the fundamentals of NumPy, including creating and working with 1D, 2D, and 3D arrays. Explored array data types, slicing notation, and the transpose attribute.

In [1]:
import numpy as np

## Array Basics

In [2]:
# 5a.
fruits = ['apple', 'banana', 'cherry', 'date']
print(fruits)

['apple', 'banana', 'cherry', 'date']


In [3]:
# 5b.
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [5]:
# 5c.
print(arr_1.dtype)

# The dtype is <U6.
# The letter U means unicode string. NumPy stores each element as a unicode string.
# The number 6 means the maximum number of characters in any string element.
# The < indicates little endian byte order.

<U6


In [8]:
# 5d.
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [9]:
# 5e.
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [11]:
print(arr_2)

# No, arr_2.T doesnt alter the value stored in arr_2.
# .T returns a VIEW of the transposed array without modifying the original.
# arr_2 still remains a 2x3 array after calling .T.

[[10 11 12]
 [13 14 15]]


In [12]:
# 5f.
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [13]:
# 5g.
# arr_3 at index position [0, 2] => row 0, col 2 => 5
# arr_3 at index position [1, 1] => row 1, col 1 => 4

arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [14]:
# 5h.
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
