# Exercise 1.A NumPy: Manipulating Arrays

In [7]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [8]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


**Difference between the first loop and the second loop:**

The first loop(`for x in arrA`) iterates over the rows of the 2D array. `x` is an entire row, so multiplying by 2 doubles every element in that row at once and prints the whole row.

The second loop(`for y in x`) iterates over each individual element within each row. So instead of printing a whole row at a time, it prints each single number multiplied by 2. The second loop gives us 6 individual printed values, while the first gives us 2 printed rows.

In [10]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# loop_result = x * 2 uses x (the row), NOT y (the individual element).
# Even though the inner loop iterates over individual elements (y)
# x * 2 dpubles the entire row, so loop_result is a 1D array like [22, 24, 26], not a single number.
# If loop_result = y * 2 is used, we would get single numbers instead.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [12]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [13]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [15]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [16]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

# It gives ValueError:all input arrays must have the same shape.
# np.stack() requires all input arrays to be of the same shape.
# joined_array_1 is shape (4, 3) and joined_array_2 has shape (2, 6)
# So NumPy raises a ValueError because arrays of different shapes can't be stacked.

ValueError: all input arrays must have the same shape

In [17]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [18]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# It gives ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2
# This fails because concatenating on axis=1 (columns) requires both arrays to have the same number of ROWS. 
# joined_array_1 has 4 rows and arrA has 2 rows
# so NumPy cannot line them up side by side as the row counts don't match.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [22]:
h_stacked = np.hstack((arrA, arrA))
print("hstack result:")
print(h_stacked)

# hstack is horizontal stack
# It joins arrays side by side (along columns, axis=1)

hstack result:
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [23]:
v_stacked = np.vstack((arrA, arrA))
print("vstack result:")
print(v_stacked)

# vstack is vertical stack 
# It joins arrays on top of each other (along rows, axis=0)

vstack result:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [25]:
d_stacked = np.dstack((arrA, arrA))
print("dstack result:")
print(d_stacked)

# dstack is depth stack 
# It joins arrays along the third axis (creates 3D array)

dstack result:
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [29]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# splitsky contains 2 arrays
# Each of the 2 resulting arrays has 2 dimensions.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [30]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# spliterino contains 3 arrays
# joined_array_1 has 4 rows; splitting into 3 gives arrays of sizes 2, 1, and 1.
# Each of the 3 resulting arrays is still 2-dimensional.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [31]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays,

In [32]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [33]:
print(arrB)

z = arrB < 7

arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [34]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
