# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [4]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[18  7]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[15  8]]


In [5]:
r_3 = np.random.random(size=(2,1))
print(r_3)

[[0.5494559 ]
 [0.38125455]]


In [6]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[62 78 53 54 71]
 [44 27 55 78 25]
 [93 88 80 90 80]
 [41 83 83 32 62]]


In [7]:
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.45919134 0.24775493 0.86694825 0.5431167  0.95879645]
 [0.02313465 0.27105276 0.62144979 0.32347109 0.11931786]
 [0.32736653 0.25303794 0.6093766  0.82986371 0.29061952]
 [0.36834406 0.88603892 0.08944224 0.76752156 0.03475476]]


## Generating Random Choices from an Array

In [8]:
students = np.array([
    "Alice", "Bob", "Charlie", "Dan", "Ethan", "Julia", "Kevin", "Hannah", "Sarah", "John", "Noah", "Ivan"
])

In [12]:
call_on = np.random.choice(students)
print(call_on)

Sarah


In [14]:
breakout_groups = np.random.choice(students, size=(3, 4), replace=False)
print(breakout_groups)

# This randomly assigns 12 students into 3 groups of 4.
# It works well as there are exactly 12 students and need 12 spots (3x4).
# replace=False ensures that no student appears twice. 
# This is an effective way to assign breakout groups because its fair, random, and unbiased.

[['Bob' 'Ivan' 'Kevin' 'Julia']
 ['Ethan' 'Dan' 'John' 'Noah']
 ['Alice' 'Charlie' 'Hannah' 'Sarah']]


In [25]:
probabilities = [0.07, 0.3, 0.07, 0.07, 0.07, 0.07, 0.0, 0.07, 0.07, 0.07, 0.07, 0.07]
call_on_weighted = np.random.choice(students, size=5, p=probabilities)
print(call_on_weighted)

# Probabilities values assigned:
# - Kevin: 0% chance (0.0)
# - Bob: 30% chance (0.3)
# - Remaining 10 students share the other 70% evenly that is 0.07 each 

['Noah' 'Ivan' 'Alice' 'Hannah' 'Noah']


In [ ]:
## Generating a Normal Distribution

In [29]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 6.54422137  9.89595115 10.29449664  6.48626146  1.76263081]
 [10.13203163 16.44118544 14.78347859 15.83578524  5.44182443]
 [ 4.07939086 11.72418645 12.64580252  5.72830535 14.19803382]
 [22.14512692 15.05967852  7.62573702  4.91236149 14.23719529]]
