# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.random(size=(2,1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.random(size=(4, 5))

## Permutations

In [4]:
print(r_4)

[[37 92 82 66 75]
 [98 42 54 88 68]
 [74 26 43 94 68]
 [30 93 25 54 34]]


In [7]:
np.random.shuffle(r_4)
print(r_4)

[[98 42 54 88 68]
 [30 93 25 54 34]
 [74 26 43 94 68]
 [37 92 82 66 75]]


Shuffle() rearranges only the ROWS of a 2D array, not individual elements.
The elements within each row stay in their original order; only the row order changes.

In [9]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

# Permutation() returns a new shuffled copy but r_4 is unchanged.
# Shuffle() modifies r_4 in place and returns None.

[[98 42 54 88 68]
 [30 93 25 54 34]
 [37 92 82 66 75]
 [74 26 43 94 68]]
[[98 42 54 88 68]
 [30 93 25 54 34]
 [74 26 43 94 68]
 [37 92 82 66 75]]


Use shuffle when you want to reorder an array in place and don't need to keep the original.
Use premutation when you need a shuffled copy and want to preserve the original array.

## Mathematical Operations

In [11]:
print(r_1, r_1.shape)
print(r_2, r_2.shape)
result = np.add(r_1, r_2)
print(result, result.shape)

[7 5] (2,)
[[14 20]] (1, 2)
[[21 25]] (1, 2)


In [12]:
print(r_1, r_1.shape)
print(r_3, r_3.shape)
result2 = np.add(r_1, r_3)
print(result2, result2.shape)

[7 5] (2,)
[[0.31950598]
 [0.80458184]] (2, 1)
[[7.31950598 5.31950598]
 [7.80458184 5.80458184]] (2, 2)


In [14]:
print(r_2, r_2.shape)
print(r_4, r_4.shape)
result3 = np.add(r_2, r_4)
print(result3, result3.shape)

# ValueError: r_2 shape (1, 2) + r_4 shape (4, 5) are not compatible.

[[14 20]] (1, 2)
[[98 42 54 88 68]
 [30 93 25 54 34]
 [74 26 43 94 68]
 [37 92 82 66 75]] (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [19]:
try: 
    print(np.add(r_1, r_4))
except ValueError as e:
    print("r_1 + r_4 error:", e)

try: 
    print(np.add(r_2, r_4))
except ValueError as e:
    print("r_2 + r_4 error:", e)

try: 
    print(np.add(r_3, r_4))
except ValueError as e:
    print("r_3 + r_4 error:", e)

# None of these are compatible with r_4 shape(4, 5)

r_1 + r_4 error: operands could not be broadcast together with shapes (2,) (4,5) 
r_2 + r_4 error: operands could not be broadcast together with shapes (1,2) (4,5) 
r_3 + r_4 error: operands could not be broadcast together with shapes (2,1) (4,5) 


In [23]:
print(np.add(np.array([1]), r_4))
# (1,) broadcasts to every element -> matches(4, 5)

[[99 43 55 89 69]
 [31 94 26 55 35]
 [75 27 44 95 69]
 [38 93 83 67 76]]


In [24]:
print(np.add(np.array([[1]]), r_4))
# (1, 1) broadcasts across rows and columns -> matches(4, 5)

[[99 43 55 89 69]
 [31 94 26 55 35]
 [75 27 44 95 69]
 [38 93 83 67 76]]


In [26]:
print(np.add(np.array([1,1,1,1,1]), r_4))
# (5,) broadcasts across each row -> matches(4, 5)

[[99 43 55 89 69]
 [31 94 26 55 35]
 [75 27 44 95 69]
 [38 93 83 67 76]]


In [28]:
print(np.add(np.array([[1],[1]]), r_4))
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting rule: NumPy compares shapes from the Right. Dimensions are compatible if they are equal or one of them is 1. The shape with 1 gets stretched to match the other. The resulting array takes the larger size in each dimension. Incompatible shapes raise ValueError.

## Rounding

In [29]:
print(r_3)

[[0.31950598]
 [0.80458184]]


In [31]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [32]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [35]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [34]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [36]:
print(np.round(r_3, 2))

[[0.32]
 [0.8 ]]


## Cumulative Operations

In [37]:
print(r_4)
print(np.sum(r_4))

[[98 42 54 88 68]
 [30 93 25 54 34]
 [74 26 43 94 68]
 [37 92 82 66 75]]
1243


In [38]:
print(np.sum(r_4, axis=0))

[239 253 204 302 245]


In [39]:
print(np.sum(r_4, axis=1))

[350 236 305 352]


In [40]:
print(np.cumsum(r_4))

[  98  140  194  282  350  380  473  498  552  586  660  686  729  823
  891  928 1020 1102 1168 1243]


In [41]:
print(np.cumsum(r_4, axis=0))

[[ 98  42  54  88  68]
 [128 135  79 142 102]
 [202 161 122 236 170]
 [239 253 204 302 245]]


## Grocery Problem

In [42]:
# [vegetables, fruits, snacks, beverages]
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [43]:
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)
print(f"The first bad contains {total_bag1} items, and the second bag contains {total_bag2} item.")

The first bad contains 9 items, and the second bag contains 7 item.


In [44]:
totals = np.add(bag1, bag2)
print(f"There are {totals[0]} vegetables, {totals[1]} fruits, {totals[2]} boxes of snacks, and {totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [45]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])

In [46]:
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [47]:
person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print(f"Ali: {person_totals[0]}, Ben: {person_totals[1]}, Carla: {person_totals[2]}")
print(f"Group total: {group_total}")

Ali: 21, Ben: 17, Carla: 16
Group total: 54


In [48]:
daily_knocks = np.sum(all_knocks, axis=0)
rolling_knocks = np.cumsum(daily_knocks)
estimated_votes = rolling_knocks * 0.5

print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
